# Use the postgres image as the base for your Docker container.

# Set the environment variable POSTGRES_PASSWORD to "docker" for the database superuser password.

# Set the environment variable POSTGRES_DB to "todo_app_db" to specify the default database name.

# Copy the todo.sql file into the /docker-entrypoint-initdb.d/ directory inside the container to execute custom initialization scripts.